<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit52f33ba441ef15cb0d96d5a2caba2290
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'N' => 
        array (
            'Notification\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Notification\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit52f33ba441ef15cb0d96d5a2caba2290::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit52f33ba441ef15cb0d96d5a2caba2290::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
